version: '3.8'

services:
  moments:
    image: liangyanjun/moments:latest
    ports:
      - "${PORT:-3000}:3000"
    environment:
      # 应用配置
      - NODE_ENV=${NODE_ENV:-production}
      
      # Notion 配置
      - NOTION_API_KEY=${NOTION_API_KEY}
      - NOTION_DATABASE_ID=${NOTION_DATABASE_ID}
      
      # 身份验证配置 (可选，留空则不启用密码保护)
      - AUTH_PASSWORD=${AUTH_PASSWORD:-}
      - JWT_SECRET=${JWT_SECRET:-}
      - SESSION_EXPIRE_HOURS=${SESSION_EXPIRE_HOURS:-24}
      
      # 文件上传配置
      - UPLOAD_DIR=${UPLOAD_DIR:-./public/uploads}
      - MAX_FILE_SIZE=${MAX_FILE_SIZE:-10485760}
      - ALLOWED_IMAGE_EXTENSIONS=${ALLOWED_IMAGE_EXTENSIONS:-jpg,jpeg,png,gif,webp}
      - ALLOWED_VIDEO_EXTENSIONS=${ALLOWED_VIDEO_EXTENSIONS:-mp4,mov,avi,mkv}
      - UPLOAD_TO_NOTION=${UPLOAD_TO_NOTION:-false}
      
      # 服务器配置
      - PORT=${PORT:-3000}
      - HOSTNAME=${HOSTNAME:-0.0.0.0}
      
      # 其他配置
      - NEXT_TELEMETRY_DISABLED=${NEXT_TELEMETRY_DISABLED:-1}
    volumes:
      # 持久化上传文件
      - ./uploads:/app/public/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 